#!/usr/bin/env php

<?php

use Clipper\App;

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

$config = [
    'rootPath' => __DIR__,
    'theme' => 'unicorn',
    'version' => '0.0.1'
];

$app = new App($config);
$app->runCommand($argv);
