#!/usr/bin/env php

<?php

use Clipper\App;

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

$app = new App();

$app->registerCommand('hello', function($argv) use ($app) {
    $name = $argv[2] ?? 'World';
    $app->print(sprintf("Hello, %s!", $name));
});

$app->registerCommand('help', function($argv) use ($app) {
    $app->print("usage: clipper name [ user=name ]");
});

$app->runCommand($argv);
