#!/usr/bin/env php

<?php

use Clipper\App;

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

$config = [
    'rootPath' => __DIR__,
    'theme' => 'unicorn',
    'version' => '0.0.1'
];

$app = new App($config);

echo $app->apply('Hello World');

$id = exec("nohup php -S 0.0.0.0:0 > /dev/null 2>&1 & echo $!", $out);

# var_dump($id);

exec("lsof -i -P | grep {$id}");

# var_dump($command);

# $app->runCommand($argv);
